spring:
  application:
    name: APIGateway

  cloud:
    gateway:
      routes:
        ## employeeservice
        - id: empservice
          uri: lb://employeeService
          predicates:
            - Path=/employee/**
          filters:
             - AuthenticationFilter 
             
        ## Authenticationservice
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/auth/**

            

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
